version: "3.7"

services:
  # MongoDB
  bot_mongo:
    image: mongo
    container_name: bot_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    restart: always

  # Discord bot
  bot_template:
    image: node:latest
    container_name: bot_template
    volumes:
      - ./:/bot
    working_dir: /bot
    entrypoint: ["/bin/sh", "-c"]
    command:
    - |
      npm i
      npm run build
      npm run start
    environment:
      MONGO: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@bot_mongo?authSource=admin
    depends_on:
      - bot_mongo
    restart: always
