version: "3.5"

services:
  # MongoDB
  # bot_mongo:
  #   image: mongo
  #   restart: always
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: example

  # Discord bot
  bot_template:
    image: node:latest
    container_name: bot_template
    volumes:
      - ./:/bot
    working_dir: /bot
    entrypoint: ["/bin/sh", "-c"]
    command:
    - |
      npm i
      npm run build
      npm run start
    restart: always
